### ISSUE TITLE
Unable to install APK

### ISSUE THREAD

**Issue by qu-rn** [axel0070/LEDBack-cover#1]
I am unable to install the APK. 
Trying it through adb gets me the following error:

`adb: failed to install com.custom.ledcover.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.custom.ledcover]`

Samsung Galaxy S10+
Android 11, OneUI 3.0

**Comment by axel7083** [comment]
Since android 11 [APK Signature Scheme v2 now required](https://developer.android.com/about/versions/11/behavior-changes-11#minimum-signature-scheme) the currently apk is only signed using v1 signature.

I made a new release fixing the signature version see [v0.1b](https://github.com/axel7083/LEDBack-cover/releases/tag/0.1b) and retry.

Note: The apk has been made for android 10, I have no idea if Samsung changed the way they manage the Ledcover. Therefore the features may not work.
